name: Ejecutar Script R

on:
  schedule:
     - cron: '0 */6 * * *'  # Ejecutar cada 6 horas
  workflow_dispatch:  # Permitir la ejecuciÃ³n manual

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configurar R
      uses: r-lib/actions/setup-r@v2
      
    - name: Cache R dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/R/Library
        key: ${{ runner.os }}-r-${{ hashFiles('**/update_sheets.R') }}-${{ hashFiles('.github/workflows/**.yml') }}
        restore-keys: |
          ${{ runner.os }}-r-
          
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          googlesheets4
          googledrive
          httr
          jsonlite
          base64enc

    - name: Create credentials file
      id: create-file
      run: |
        echo '${{ secrets.OAUTH_TOKEN }}' > credentials.json

    - name: Autenticar y ejecutar script R
      env:
        GDRIVE_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        IMPORTACIONES_URL: ${{ secrets.IMPORTACIONES_URL }}
        CREDENCIALES_URL: ${{ secrets.CREDENCIALES_URL }}
      run: |
        Rscript update_sheets.R
